name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

# The following defines the version and build number for your application.
environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # to add a dependency to your application, add an dependencies section, like this:
  cupertino_icons: ^1.0.6
  go_router: ^14.2.7

  # dependencies for my local storage using shared preferences
  shared_preferences: ^2.2.3

  # dependency for my services
  get_it: ^7.7.0

  # dependencies for my state management
  flutter_bloc: ^8.1.6

  # firebase dependencies
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2

  # dependencies 
  cherry_toast: ^1.11.0
  email_validator: ^3.0.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_svg: ^2.0.10+1
  crypto: ^3.0.5
  http: ^1.2.2
  redacted: ^1.0.12
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1


# Dev dependencies specify other packages that your package needs in order to work.
dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter packages pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/image.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/image.png"

  # The "flutter_lints" package below contains a set of recommended lints to 
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/auth/
    - assets/images/banners/
    - assets/images/bottom_nav_bar/
    - assets/images/categories/
    - assets/images/location/
    - assets/images/products/
    - assets/images/icons/
    - assets/images/logo_splash.png

  # to add fonts to your application, add a fonts section here,
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira_Condensed-Regular.ttf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart